version: '3.8'

services:
  ghost:
    image: ghost:latest
    container_name: ghost-cms
    restart: always
    ports:
      - "2368:2368"
    environment:
      url: http://localhost:2368
      database__client: sqlite3
      database__connection__filename: "/var/lib/ghost/content/data/ghost-dev.db"
      NODE_ENV: development
    volumes:
      - ghost-data:/var/lib/ghost/content

  ghost-tests:
    build: .
    container_name: ghost-automation
    depends_on:
      - ghost
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
    
volumes:
  ghost-data: